#!/bin/bash
file="/etc/crontab"
result="/etc/crontab_md5"
final_result="/tmp/final_result.txt"

if [ ! -e $result ]; then
	md5sum $file | awk '{print $1}' > $result
	exit 1
fi

md5sum $file | awk '{print $1, $result}' > $final_result
if [[ ! md5sum -c $final_result ]]; then
	mail -s '$file modified' root@localhost <<END
	crontab file has been modified
END
fi

# pour cron: 0 0 * * * [PATH_TO]/roger_skyline_1/Scripting/04
